name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Tokyo"
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN_FOR_PACKAGE }}

      - name: Build Docker image
        run: |
          TAG=${GITHUB_REF##*/}
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$TAG \
                       -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest \
                       --label "org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/${{ github.repository }}" .

      - name: Push Docker image
        run: |
          TAG=${GITHUB_REF##*/}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$TAG
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
